apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: http-svc-ingress
  namespaces: test
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /httpsvc
        backend:
          serviceName: http-svc
          servicePort: 80
  
